const ApiStrings = {
    LOGIN:'/users/login',
    ME:'/users/me',
    LOGOUT:'/users/logout',
    CHANGE_PASSWORD:'/users/change-password',
    RESET_PASSWORD:'/users/reset-password',
    UPDATE_EMAIL:'/users/change-email',
    DELETE_PROFILE:(fileId:string) => `/users/delete/${fileId}`,
    UPDATE_PROFILE:'/users/update-profile',
    SIGNUP:'/users/register',
    RESEND_OTP:'/users/resend-otp',
    ADD_FOLLOWUP: (id:string) => `/masjids/follow-up/${id}` ,
    ADD_MARK_COMPLETE: (id:string) => `/masjids/complete/${id}` ,
    OTP_VERIFY:'/users/otp-verify',
    OTP_CHECK:'/users/otp-check',
    KYC_VERIFY:'/users/kyc-verify',
    REQUEST_TO_ADMIN:'/masjids/request-access',
    GET_MASJIDS_NAME:'/masjids/masjid-name',
    CREATE_REHEB:'/masjids/create',
    GET_REPORT: (id:string) => `/masjids/rehabilitation-report/${id}`,
    GET_MASJIDS_MODERATOR:'/masjids/moderator/info',
    GET_MASJID_DETAILS: (id:string) => `/masjids/details/${id}`,
    GET_MASJID_REHEB_PEOPLE: (id:string) => `/masjids/rehabilitation/${id}`,
    GET_MASJID_REHEB_STATS: (id:string) => `/masjids/rehabilitation-stats/${id}`,
    GET_MASJID_DETAILS_FOR_MODERATOR:`/masjids/moderator/stats`,
    CREATE_PEOPLE: (ID:string) => `poor-people/${ID}/poor-person`,
    COMMITTEE_PROFILE_DELETE: (masjidId:string, committeeId:string) => `committee/${masjidId}/committee/${committeeId}/image`,
    CREATE_COMMITTEE:'/committee/create',
    GET_MASJIDS:'/users/home-search',
    UPDATE_COMMITTEE: '/committee/update',
    GET_NOTIFICATIONS: (userId:string) => `/notifications/${userId}`,
    READ_NOTIFICATION: (notificationId:string) => `/notifications/read/${notificationId}`,
    SAVE_FCM_TOKEN: `/users/save-token`,
    DELETE_NOTIFICATION:(id:string) => `/notifications/${id}`,
    GET_REQUEST_HISTORY: `/users/requests-history`,
    DONATION_PEOPLE:`/donation/create`,
    GET_DONATIONS: (id:string) => `/donation/${id}`,
}

export default ApiStrings