export const Fonts = {
    QUICKSAND_BOLD: 'Quicksand-Bold',
    QUICKSAND_LIGHT: 'Quicksand-Light',
    QUICKSAND_MEDIUM: 'Quicksand-Medium',
    QUICKSAND_REGULAR: 'Quicksand-Regular',
    QUICKSAND_SEMIBOLD: 'Quicksand-SemiBold',
}

export const AppFonts = {
  heading1Regular: {
    fontFamily: 'Quicksand-Regular',
    fontSize: '48@ms',
    lineHeight: '58@ms',
    letterSpacing: '-0.2@ms',
    fontWeight: '400',
  },
  heading1Medium: {
    fontFamily: 'Quicksand-Medium',
    fontSize: '48@ms',
    lineHeight: '58@ms',
    letterSpacing: '-0.2@ms',
    fontWeight: '500',
  },
  heading1SemiBold: {
    fontFamily: 'Quicksand-SemiBold',
    fontSize: '48@ms',
    lineHeight: '58@ms',
    letterSpacing: '-0.2@ms',
    fontWeight: '600',
  },
  heading1Bold: {
    fontFamily: 'Quicksand-Bold',
    fontSize: '48@ms',
    lineHeight: '58@ms',
    letterSpacing: '-0.2@ms',
    fontWeight: '700',
  },

  heading2Regular: {
    fontFamily: 'Quicksand-Regular',
    fontSize: '40@ms',
    lineHeight: '48@ms',
    letterSpacing: '-0.2@ms',
    fontWeight: '400',
  },
  heading2Medium: {
    fontFamily: 'Quicksand-Medium',
    fontSize: '40@ms',
    lineHeight: '48@ms',
    letterSpacing: '-0.2@ms',
    fontWeight: '500',
  },
  heading2SemiBold: {
    fontFamily: 'Quicksand-SemiBold',
    fontSize: '40@ms',
    lineHeight: '48@ms',
    letterSpacing: '-0.2@ms',
    fontWeight: '600',
  },
  heading2Bold: {
    fontFamily: 'Quicksand-Bold',
    fontSize: '40@ms',
    lineHeight: '48@ms',
    letterSpacing: '-0.2@ms',
    fontWeight: '700',
  },

  heading3Regular: {
    fontFamily: 'Quicksand-Regular',
    fontSize: '32@ms',
    lineHeight: '48@ms',
    letterSpacing: '-0.2@ms',
    fontWeight: '400',
  },
  heading3Medium: {
    fontFamily: 'Quicksand-Medium',
    fontSize: '32@ms',
    lineHeight: '48@ms',
    letterSpacing: '-0.2@ms',
    fontWeight: '500',
  },
  heading3SemiBold: {
    fontFamily: 'Quicksand-SemiBold',
    fontSize: '32@ms',
    lineHeight: '48@ms',
    letterSpacing: '-0.2@ms',
    fontWeight: '600',
  },
  heading3Bold: {
    fontFamily: 'Quicksand-Bold',
    fontSize: '32@ms',
    lineHeight: '48@ms',
    letterSpacing: '-0.2@ms',
    fontWeight: '700',
  },
  heading4Regular: {
    fontFamily: 'Quicksand-Regular',
    fontSize: '28@ms',
    lineHeight: '48@ms',
    letterSpacing: '-0.2@ms',
    fontWeight: '400',
  },
  heading4Medium: {
    fontFamily: 'Quicksand-Medium',
    fontSize: '28@ms',
    lineHeight: '48@ms',
    letterSpacing: '-0.2@ms',
    fontWeight: '500',
  },
  heading4SemiBold: {
    fontFamily: 'Quicksand-SemiBold',
    fontSize: '28@ms',
    lineHeight: '48@ms',
    letterSpacing: '-0.2@ms',
    fontWeight: '600',
  },
  heading4Bold: {
    fontFamily: 'Quicksand-Bold',
    fontSize: '28@ms',
    lineHeight: '48@ms',
    letterSpacing: '-0.2@ms',
    fontWeight: '700',
  },
  heading5Regular: {
    fontFamily: 'Quicksand-Regular',
    fontSize: '24@ms',
    lineHeight: '48@ms',
    letterSpacing: '-0.2@ms',
    fontWeight: '400',
  },
  heading5Medium: {
    fontFamily: 'Quicksand-Medium',
    fontSize: '24@ms',
    lineHeight: '48@ms',
    letterSpacing: '-0.2@ms',
    fontWeight: '500',
  },
  heading5SemiBold: {
    fontFamily: 'Quicksand-SemiBold',
    fontSize: '24@ms',
    lineHeight: '48@ms',
    letterSpacing: '-0.2@ms',
    fontWeight: '600',
  },
  heading5Bold: {
    fontFamily: 'Quicksand-Bold',
    fontSize: '24@ms',
    lineHeight: '48@ms',
    letterSpacing: '-0.2@ms',
    fontWeight: '700',
  },
  heading6Regular: {
    fontFamily: 'Quicksand-Regular',
    fontSize: '20@ms',
    lineHeight: '48@ms',
    letterSpacing: '-0.2@ms',
    fontWeight: '400',
  },
  heading6Medium: {
    fontFamily: 'Quicksand-Medium',
    fontSize: '20@ms',
    lineHeight: '48@ms',
    letterSpacing: '-0.2@ms',
    fontWeight: '500',
  },
  heading6SemiBold: {
    fontFamily: 'Quicksand-SemiBold',
    fontSize: '20@ms',
    lineHeight: '48@ms',
    letterSpacing: '-0.2@ms',
    fontWeight: '600',
  },
  heading6Bold: {
    fontFamily: 'Quicksand-Bold',
    fontSize: '20@ms',
    lineHeight: '48@ms',
    letterSpacing: '-0.2@ms',
    fontWeight: '700',
  },
  paragraphLargeRegular: {
    fontFamily: 'Quicksand-Regular',
    fontSize: '18@ms',
    lineHeight: '26@ms',
    letterSpacing: '0@ms',
    fontWeight: '400',
  },
  paragraphLargeMedium: {
    fontFamily: 'Quicksand-Medium',
    fontSize: '18@ms',
    lineHeight: '26@ms',
    letterSpacing: '0@ms',
    fontWeight: '500',
  },
  paragraphLargeSemiBold: {
    fontFamily: 'Quicksand-SemiBold',
    fontSize: '18@ms',
    lineHeight: '26@ms',
    letterSpacing: '0@ms',
    fontWeight: '600',
  },
  paragraphLargeBold: {
    fontFamily: 'Quicksand-Bold',
    fontSize: '18@ms',
    lineHeight: '26@ms',
    letterSpacing: '0@ms',
    fontWeight: '700',
  },

  paragraphMediumRegular: {
    fontFamily: 'Quicksand-Regular',
    fontSize: '16@ms',
    lineHeight: '24@ms',
    letterSpacing: '0@ms',
    fontWeight: '400',
  },
  paragraphMediumMedium: {
    fontFamily: 'Quicksand-Medium',
    fontSize: '16@ms',
    lineHeight: '24@ms',
    letterSpacing: '0@ms',
    fontWeight: '500',
  },
  paragraphMediumSemiBold: {
    fontFamily: 'Quicksand-SemiBold',
    fontSize: '16@ms',
    lineHeight: '24@ms',
    letterSpacing: '0@ms',
    fontWeight: '600',
  },
  paragraphMediumBold: {
    fontFamily: 'Quicksand-Bold',
    fontSize: '16@ms',
    lineHeight: '24@ms',
    letterSpacing: '0@ms',
    fontWeight: '700',
  },

  paragraphSmallRegular: {
    fontFamily: 'Quicksand-Regular',
    fontSize: '14@ms',
    lineHeight: '20@ms',
    letterSpacing: '0@ms',
    fontWeight: '400',
  },
  paragraphSmallMedium: {
    fontFamily: 'Quicksand-Medium',
    fontSize: '14@ms',
    lineHeight: '20@ms',
    letterSpacing: '0@ms',
    fontWeight: '500',
  },
  paragraphSmallSemiBold: {
    fontFamily: 'Quicksand-SemiBold',
    fontSize: '14@ms',
    lineHeight: '20@ms',
    letterSpacing: '0@ms',
    fontWeight: '600',
  },
  paragraphSmallBold: {
    fontFamily: 'Quicksand-Bold',
    fontSize: '14@ms',
    lineHeight: '20@ms',
    letterSpacing: '0@ms',
    fontWeight: '700',
  },

  paragraphXSmallRegular: {
    fontFamily: 'Quicksand-Regular',
    fontSize: '12@ms',
    lineHeight: '18@ms',
    letterSpacing: '0@ms',
    fontWeight: '400',
  },
  paragraphXSmallMedium: {
    fontFamily: 'Quicksand-Medium',
    fontSize: '12@ms',
    lineHeight: '18@ms',
    letterSpacing: '0@ms',
    fontWeight: '500',
  },
  paragraphXSmallSemiBold: {
    fontFamily: 'Quicksand-SemiBold',
    fontSize: '12@ms',
    lineHeight: '18@ms',
    letterSpacing: '0@ms',
    fontWeight: '600',
  },
  paragraphXSmallBold: {
    fontFamily: 'Quicksand-Bold',
    fontSize: '12@ms',
    lineHeight: '18@ms',
    letterSpacing: '0@ms',
    fontWeight: '700',
  },
  labelLarge: {
    fontSize: 16,
    fontWeight: '600',
    color: '#000',
  },
  errorText: {
    fontSize: 12,
    color: 'red',
  },
}